import 'package:autism/features/privacy/data/models/legal_info_model.dart';

class LegalInfoRepository {
  // Create a LegalInfoModel object with all legal items
  LegalInfoModel getLegalInfo() {
    return LegalInfoModel(items: [
      LegalInfoItem(
          title: "Terms, Conditions & Disclaimer",
          content:
              "This application (\"App\"), designed for the early detection and management of autism, is developed and operated by [Your Company Name] (\"Company\", \"we\", \"us\", or \"our\"). The App provides services such as AI-based analysis of children's drawings, educational resources, and access to consultations with specialists (\"Services\"). By accessing or using the App, you agree to comply with these Terms and Conditions, including the disclaimers outlined below. If you do not agree, you must discontinue using the App immediately."),
      LegalInfoItem(
          title: "Disclaimer",
          content:
              "We strive to provide accurate and reliable information through the App. However, all content and services offered are provided on an “as-is” basis without any warranties, express or implied. We make no representations or guarantees regarding the accuracy, completeness, or results derived from the use of the Services."),
      LegalInfoItem(
          title: "Medical Disclaimer",
          content:
              "The information and results generated by the App are intended solely for informational purposes. The AI analysis, educational content, and consultations should **not** be considered as a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of a qualified healthcare provider for any medical concerns or before making decisions about your child's health. The App does not replace medical consultations or therapy prescribed by healthcare professionals."),
      LegalInfoItem(
          title: "Legal Disclaimer",
          content:
              "Any legal information provided in the App is for general informational purposes only and should not be construed as legal advice. We recommend that you consult with a qualified attorney for legal matters that pertain to your specific situation. The use of any legal content in the App does not establish a lawyer-client relationship."),
      LegalInfoItem(
          title: "Therapy and Behavioral Disclaimer",
          content:
              "The information provided in the App about autism, behavioral therapy, speech therapy, or other related topics is general in nature and not tailored to individual cases. This content is not intended to replace professional therapy provided by certified therapists. Outcomes may vary from person to person, and the Company does not guarantee specific results from the use of the information provided."),
      LegalInfoItem(
          title: "Limitation of Liability",
          content:
              "We are not liable for any direct, indirect, incidental, special, or consequential damages, including but not limited to, loss of data, personal injury, or interruption of business, arising from the use of or inability to use the App or the Services. In no event shall our total liability exceed the amount paid by you, if any, for access to the Services."),
      LegalInfoItem(
          title: "Indemnity",
          content:
              "You agree to indemnify and hold [Your Company Name] harmless from any claims, liabilities, damages, or legal fees that may arise from your use of the App, your violation of these Terms, or any infringement of third-party rights."),
      LegalInfoItem(
          title: "Account Registration",
          content:
              "When registering for an account on the App, you agree to provide accurate and current information. You are responsible for maintaining the security and confidentiality of your account credentials. You must notify us immediately if you suspect any unauthorized use of your account. We are not responsible for any losses or damages resulting from unauthorized access to your account due to your failure to safeguard your credentials."),
      LegalInfoItem(
          title: "Permitted Use of the App",
          content:
              "The App may only be used for lawful purposes. Any abuse, misuse, or illegal activity, including but not limited to hacking, fraud, or any actions that violate these Terms, will result in immediate termination of your access to the App and its Services."),
      LegalInfoItem(
          title: "Privacy",
          content:
              "We respect your privacy and are committed to protecting your personal information. The collection and use of your data are governed by our Privacy Policy, which complies with applicable data protection laws. By using the App, you agree to the terms of our Privacy Policy, available within the App."),
      LegalInfoItem(
          title: "Governing Law",
          content:
              "These Terms and any disputes related to them shall be governed by and construed in accordance with the laws of [Your State/Country]. Any legal actions arising from these Terms or your use of the App shall be brought exclusively in the courts of [Your Jurisdiction]."),
    ]);
  }
}
